### ISSUE TITLE
No hamburger menu on 4.6 on mobile

### ISSUE THREAD

**Issue by sralsg** [aghstrategies/com.aghstrategies.slicknav#1]
We aren't having any luck with the responsiveness on 4.6.21. No effect on Chrome/Android or on Safari/IOS. I can get (oddly) three identical hamburger menus to show up in Chrome/OSX by resizing the window, but not with the simulated mobile devices.

**Comment by colemanw** [comment]
Can you give more details?
This commit ought to fix the multiple menus issue: a8ac9c19173feda5be61d4b44885f4214b64b652

**Comment by sralsg** [comment]
We just get nothing changed on mobile, no hamburger menu and the menu looks the same as it always has. Also tried the mobile device simulation in Chrome and have the same results. Happy to provide details, but not sure what would be useful.

**Comment by colemanw** [comment]
Strange, the same thing happens to me in my Chrome device simulator; although it does work in a normal narrow window on Chrome.
Any ideas @alifrumin?

**Comment by christianwach** [comment]
@colemanw @sralsg There does seem to be some strange behaviour in Chrome's simulator, but it's hard to pin down. It seems that the zoom levels are a bit messed up when switching to it and when switching between device simulators. Hitting the `rotate` button a few times seems to reset it for me, though sometimes I have to pop the Inspector out into a separate window for the zoom levels to reset. All quite annoying.

Once I have the correct zoom, the menu works for me on any page that's not primarily table-based content, e.g. System Status. On pages with table-based content, there's an overflow of content out of the viewport which pushes the hamburger offscreen. This applies to Civi 4.7.x too of course - it's a result of the viewport no longer matching the `<html>` width. Try setting `width: 100%;` on the `<html>` element and you should see the menu behave - but then you're unable to view the table content that's overflowing the viewport!

(On WordPress, the Civi menu also overlays the WordPress menu hamburger such that it is not possible to navigate away from Civi, though I guess that's a separate issue.)

**Comment by sralsg** [comment]
The Chrome simulator might be a bit of a red herring, because actual mobile devices is the real issue.

**Comment by alifrumin** [comment]
@sralsg @colemanw @christianwach hey guys, @sralsg thank you for bringing this to our attention. I added a "max-device-width" to the media query and that fixed it for me commit: https://github.com/aghstrategies/com.aghstrategies.slicknav/commit/eceae76c1ce66654a97b81ffcfe5a3191bc4b3fc let me know if that fixes it for you.

**Comment by sralsg** [comment]
@colemanw @christianwach @alifrumin Works! Thanks @alifrumin
