### ISSUE TITLE
Not working on Windows Phone 8.1, iPad Mini 2, iPad 2

### ISSUE THREAD

**Issue by sleewok** [aghstrategies/com.aghstrategies.slicknav#3]
The code in civislicknav.js.tpl is not executed on these devices.

**Comment by sleewok** [comment]
Figured out the problem. The devices were accessing the site via HTTP rather than HTTPS, which is marked as required. The js.tpl file was being served as HTTPS and therefore was getting rejected.

**Comment by alifrumin** [comment]
@sleewok appreciate your interest, glad that you worked it out.
