### ISSUE TITLE
Mobile Menu Logo Image Link Dead

### ISSUE THREAD

**Issue by sleewok** [aghstrategies/com.aghstrategies.slicknav#5]
In the latest Civi release the logo image used for the mobile menu is dead. 

The original image was: logo16px.png
It is now: logo_sm.png

civislicknav.js.tpl needs the following line changed to:
`label: '<img src="' + CRM.config.resourceBase + 'i/logo_sm.png">',`

**Comment by colemanw** [comment]
@sleewok can you submit a pull-request? You can click the pencil icon while looking at the file in question on GitHub to do so.

**Comment by sleewok** [comment]
Will do tomorrow.

**Comment by alifrumin** [comment]
https://github.com/aghstrategies/com.aghstrategies.slicknav/pull/6 has been merged I think this issue is now resolved. THANK YOU @sleewok and @colemanw
